### PR TITLE
fix: strip translations with an empty string as value

### LINKED ISSUE #1512: Should "stripEmptyTranslations" also strip actual empty strings?
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: **v3.24.0**
- Ember CLI Version: **v3.24.0**
- Ember Intl Version: **v5.6.2**
- Browser(s): /
- Node Version: **v12.20.1**

`stripEmptyTranslations` description in the docs is as follows:
> At build time, removes empty translation keys if their values are falsey.

Reading this (and also based on the config name) I would expect that empty strings (`""`) would be stripped from the final build as well, however this doesn't seem to be the case.

Would it be possible to strip actual empty strings as well or is this not advised/possible?

If you guys think this is okay, I'm willing to create a PR.

If not, can we update the docs to state that only `null` values are stripped to make it more clear?

### PR DESCRIPTION
**Pull request by bertdeblock**
Closes #1512.

### CODE REVIEW

File: lib/broccoli/translation-reducer/index.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const fs = require('fs');
 const Linter = require('./linter');
 const forEachMessage = require('./utils/for-each-message');
 const validateMessage = require('../../message-validator/validate-message');
-const stripNestedNulls = require('./utils/strip-nested-nulls');
+const stripEmptyTranslations = require('./utils/strip-empty-translations');
```
Comment (bertdeblock) [inline lib/broccoli/translation-reducer/index.js:19]: Renamed the helper because now it does more than stripping nested `null`s.

File: lib/broccoli/translation-reducer/utils/strip-empty-translations.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+function stripEmptyTranslations(object, objectKey, objectParent) {
+  Object.keys(object).forEach((key) => {
+    const keyValue = object[key];
+
+    if (keyValue === null || keyValue === '') {
+      delete object[key];
+
+      const isObjectEmpty = Object.keys(object).length === 0;
+
+      if (isObjectEmpty && objectParent) {
```
Comment (bertdeblock) [inline lib/broccoli/translation-reducer/utils/strip-empty-translations.js:22]: I added this part as well so it doesn't leave behind empty objects. Let me know if this change is too drastic and I'll remove.

**Comment by longlho** [comment]
Thanks a lot for your contributions!
