### PR TITLE
fix: Do not report missing ICU arguments for locales that have not implemented translation.

### LINKED ISSUE #1218: Ability to silence "ICU argument missing" warnings for missing/non-translated keys
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.9.0
- Ember CLI Version: 3.9.0
- Ember Intl Version: 4.2.4
- Browser(s): N/A
- Node Version: 13.11.0

### Steps to Reproduce

1. Using `requiresTranslation` in `ember-intl.js` config to silence missing translations for the non-default locale works fine
	```js
		module.exports = function() {
  			return {
    			disablePolyfill: true,
    			publicOnly: true,
    			requiresTranslation(key, locale) {
      				return locale === 'en-us';
    			}
  			};
		};
	```

2. If the `en-us` translation uses arguments in a translation key and the other locales are not translated then "ICU argument missing warnings" appear for the key
3. Building the ember application spams the build log with over a thousand lines of ICU warnings (I have ~55 translation files with most in the early stages/less than 10%)
4. Valid errors in `en-us` or locale translation mistakes are buried

I've read through the docs but haven't stumbled upon anything that would achieve this.

en-us.yaml
```yml
timeUnits:
  years: "{count, plural, =1 {year} other {years}}"
string: "Example"
```

es-es.yaml
```yml
string: "Ejemplo"
```

build output
```
[ember-intl] "timeUnits.years" ICU argument missing: "es-es": "count"
```

image

### LINKED ISSUE #1283: Missing ICU argument warnings still appear for keys not present in 5.0.6
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

5.0.0 added https://github.com/ember-intl/ember-intl/pull/1224 which was intended to suppress missing ICU argument warnings for keys not present in a given localisation file (while still warning if the key is missing for required translations). However it appears to still be warning for the same keys as in 4.2.4 before the PR was merged.

### Environment

- Ember Version: 3.9.1
- Ember CLI Version: 3.9.0
- Ember Intl Version: 5.0.6
- Browser(s): N/A
- Node Version: 14.1.0

### Steps to Reproduce

1. Config:

```js
module.exports = function() {
  return {
    publicOnly: true,
    requiresTranslation(key, locale) {
      return locale === 'en-us';
    }
  };
};
```

2. `en-us.yaml`:

```yaml
hello: "World"
timeUnits:
  days: "{count, plural, =1 {day} other {days}}"
```

3. `af-za.yaml`:

```yaml
hello: "World"
```

4. Build log:

```
[ember-intl] "timeUnits.days" ICU argument missing: "af-za": "count"
```

### PR DESCRIPTION
**Pull request by jasonmit**
fixes #1218, #1283

Also reverts a behavior that shouldn't have been added where if you used `fallbackLocale` it opted you out of ICU argument mismatch checking.

### CODE REVIEW

**Comment by jasonmit** [comment]
@wopian when you get a chance can you verify this will resolve your issues?  I had to change a bit of the logic.

Basically ember-intl will now never alert on matching ICU arguments for locales that do not implement a missing translation.

File: tests-node/unit/broccoli/translation-reducer/find-missing-translations-test.js [hunk 1]
```diff
@@ -22,17 +20,6 @@ describe('findMissingTranslations', function () {
       ['en', ['bar']],
     ];
 
-    expect(findMissingTranslations(key, localeKeys, isTrue)).to.deep.equal(['en']);
-  });
-
-  it('ignores missing translations if not required', function () {
```
Comment (jasonmit) [inline tests-node/unit/broccoli/translation-reducer/find-missing-translations-test.js:28]: Rewrite test as part of a Linter unit/integration test now that this logic doesn't live within `findLocalesMissingTranslation`

File: lib/broccoli/translation-reducer/linter/find-missing-icu-arguments.js [hunk 2]
```diff
@@ -1,6 +1,7 @@
 function findMissingIcuArguments(key, allIcuArguments, locales, icuArguments) {
   const keyIcuArguments = Array.from(allIcuArguments[key]);
-  return locales
+
+  const result = locales
```
Comment (wopian) [inline lib/broccoli/translation-reducer/linter/find-missing-icu-arguments.js:4]: This could just be

```js
return locales
	.map((locale) => [
		locale,
		keyIcuArguments.filter((arg) => 
			!Object.prototype.hasOwnProperty.call(icuArguments[locale], key) || 
			!icuArguments[locale][key].includes(arg)
      	),
    ])
    .filter(([, missing]) => missing.length > 0);
```

File: lib/broccoli/translation-reducer/linter/find-missing-translations.js [hunk 3]
```diff
@@ -1,7 +1,13 @@
-function findMissingTranslations(key, localeKeys, requiresTranslation) {
-  return localeKeys
-    .filter(([locale, translationKeys]) => !translationKeys.includes(key) && requiresTranslation(key, locale))
-    .map(([locale]) => locale);
+function findLocalesMissingTranslation(key, localeKeys) {
+  const result = localeKeys
```
Comment (wopian) [inline lib/broccoli/translation-reducer/linter/find-missing-translations.js:2]: Same here

File: lib/broccoli/translation-reducer/linter/find-missing-icu-arguments.js (hunk 2 above)
Comment (jasonmit) [reply lib/broccoli/translation-reducer/linter/find-missing-icu-arguments.js:4]: Makes future debugging slightly easier, going to leave this as-is

File: lib/broccoli/translation-reducer/linter/find-missing-translations.js (hunk 3 above)
Comment (jasonmit) [reply lib/broccoli/translation-reducer/linter/find-missing-translations.js:2]: Same as above, makes debugging a little easier so will keep as-is

File: lib/broccoli/translation-reducer/index.js [hunk 4]
```diff
@@ -222,6 +219,11 @@ class TranslationReducer extends CachingWriter {
         encoding: 'utf8',
       });
     }
+
+    // Note: lint after the fallback has been merged in
+    const lintResults = this.linter.lint(translations);
```
Comment (jasonmit) [inline lib/broccoli/translation-reducer/index.js:224]: This will break fallbackLocale since we'll never know if a translation is missing in order for errorOnMissingTranslations to continue to behave as-is.  May need to move this.

I really dislike most of the linting logic and configuration, may end up rewriting it all.

File: lib/broccoli/translation-reducer/linter/index.js [hunk 5]
```diff
@@ -44,25 +44,31 @@ module.exports = class Linter {
...
-        result.missingTranslations.push([key, notInLocales]);
-      }
-
-      let missingICUArgs = findMissingICUArguments(key, allIcuArguments, locales, icuArguments);
+      if (translationMissingFromLocales.length) {
+        const alertableMissingTranslations = translationMissingFromLocales.filter((locale) =>
+          requiresTranslation(key, locale)
+        );
 
-      if (fallbackLocale) {
```
Comment (jasonmit) [inline lib/broccoli/translation-reducer/linter/index.js:58]: This logic isn't right.  If there is a `fallbackLocale` it shouldn't have a side effect of disabling linting other locales for mismatch ICU arguments.

**Comment by sandstrom** [comment]
@jasonmit I've tried this code and it works great for me too!

Sorry if I introduced any issues with my earlier PR that attempted to tackle this! 🙏 

There is one lingering mismatch warning around, https://github.com/ember-intl/ember-intl/issues/1288

But overall this is a great improvement! 😄

**Comment by jasonmit** [comment]
@sandstrom awesome, glad it worked out 😅

> Sorry if I introduced any issues with my earlier PR that attempted to tackle this!

Totally not your fault, the linter has grown into something somewhat confusing to extend.  I'm going to try and fix that in the future.

**Comment by sandstrom** [comment]
@jasonmit The linter is great though, it really helps in keeping locale files up to date and aligned.
